version: "3.9"

services:
  frontend:
    image: majat4/llm-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

  api:
    image: majat4/llm-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"
