version: "3.9"

services:
  frontend:
    image: dt1_frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

  api:
    image: dt1_api:latest
    ports:
      - "5001:5001"
