services:
  frontend:
    image: majat4/dt1-frontend:v1
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

  api:
    image: majat4/dt1-backend:v1
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"