services:
  frontend:
HEAD
    image: majat4/llm-frontend:latest
    image: majat4/dt1-frontend:v1
e6a9214ab3a87a9d686c351ac987c3cf596b20fc
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

  api:
HEAD
    image: majat4/llm-api:latest
    image: majat4/dt1-backend:v1
e6a9214ab3a87a9d686c351ac987c3cf596b20fc
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5001:5001"